package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResponseParserImpl implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	org.slf4j.Logger logger = org.slf4j.LoggerFactory
			.getLogger(ResponseParserImpl.class);

	public ResponseParserImpl() {
	}

	public void parseResponse(
			org.kie.api.runtime.process.ProcessContext kcontext) {
		try {
			// java.util.Map<String, String> responseMap =
			// (java.util.LinkedHashMap<String, String>) kcontext
			// .getVariable("response");

			org.json.JSONObject responseJSON = new org.json.JSONObject(
					(kcontext.getVariable("response")).toString());
			// logger.info("Response Json:" + responseJSON);

			kcontext.setVariable("city", responseJSON.getString("title"));
			logger.info("City Name is : "
					+ String.valueOf(kcontext.getVariable("city")));

			org.json.JSONArray getArray = responseJSON
					.getJSONArray("consolidated_weather");

			// logger.info("Response Json Array:" + getArray);

			for (int i = 0; i < getArray.length(); i++) {
				org.json.JSONObject objects = getArray.getJSONObject(i);
				java.util.Iterator key = objects.keys();
				while (key.hasNext()) {
					String jsonkey = key.next().toString();
					if (jsonkey.equalsIgnoreCase("weather_state_name")) {
						logger.info("Key : " + jsonkey + ", value : "
								+ objects.getString(jsonkey));
					}
				}
				// System.out.println(objects.toString());
				System.out.println("-----------");

			}

		} catch (Exception e) {
			// return e.getMessage();
			logger.info("ERROR:" + e.getMessage());
		}
	}

	public ResponseParserImpl(org.slf4j.Logger logger) {
		this.logger = logger;
	}

}