package com.myspace.restworkitemhandlerdemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PropertiesLoader implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public PropertiesLoader() {
	}

	private static final org.slf4j.Logger LOGGER = org.slf4j.LoggerFactory
			.getLogger(PropertiesLoader.class);

	public java.util.Properties getProperties(String propertiesFileName) {
		String CONFIG_DIR_PROPERTY = "jboss.server.config.dir";
		// String propertiesFileName = "customRest.properties";
		String path = System.getProperty(CONFIG_DIR_PROPERTY)
				+ java.io.File.separator + propertiesFileName;
		LOGGER.info("ApplicationConfigurationLoader properties file location path is :"
				+ path + "\n");
		java.util.Properties properties = new java.util.Properties();
		try {
			properties.load(new java.io.FileInputStream(path));
		} catch (java.io.FileNotFoundException e) {
			LOGGER.info("An exception occured" + e.getMessage());
		} catch (java.io.IOException e) {
			LOGGER.info("An exception occured" + e.getMessage());
		}
		return properties;
	}

}